name: Tests

on:
  push:
    branches: [main, pypi-package]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
          use-mamba: true  # faster dependency resolution

      - name: Install GDAL via Conda
        run: |
          conda install -y -c conda-forge gdal

      - name: Install package dependencies
        run: |
          pip install -e .[test]

      - name: Run tests
        run: pytest -v
